### ISSUE TITLE
OAuth2 Bearer token in Authorization header

### ISSUE THREAD

**Issue by ekampp** [graphiti-api/vandal#5]
Hey. 

How would I go about adding OAuth2 authentication to this API explorer? 

Best,
Emil

**Comment by richmolj** [comment]
I use request.ly !

**Comment by ekampp** [comment]
Hi, @richmolj. I'm not sure what that is. Can you provide a link?

**Comment by richmolj** [comment]
https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa?hl=en

**Comment by ekampp** [comment]
That's _a solution_, but not really what I was needing, and not really usable when presenting the interactive API explorer to an external developer.

**Comment by richmolj** [comment]
Sure, I'd be happy to merge a PR if this is functionality you'd like to add, but request.ly works/is preferable for my purposes

**Comment by ekampp** [comment]
I didn't open the issue to make sure your needs are met. 🤷🏻‍♂️

**Comment by richmolj** [comment]
And I didn't create this library to make sure yours were 🙂  This is open-source software you can choose to improve, or go with another solution.

**Comment by ekampp** [comment]
And I did try to open up a discussion about improving it, but it seems that you're not really interested—a shame.

**Comment by ekampp** [comment]
I'm not going to spend time and energy on a PR without discussing to make sure it will eventually be merged. I will close this Issue and find another tool.
